### ISSUE TITLE
[Bug]: 元数据加载完成前意外允许导入祈愿记录

### ISSUE THREAD

**Issue by misaka10384** [DGP-Studio/Snap.Hutao#105]
### Windows 版本

windows 11 版本: 25217.1010

### Snap Hutao 版本

1.1.9.0

### 发生了什么？

使用json导入祈愿记录时软件崩溃 重启后无法导入记录
json是通过sg导出的json
日志
[Log.zip](https://github.com/DGP-Studio/Snap.Hutao/files/9777018/Log.zip)
录像
https://user-images.githubusercontent.com/61707010/195607463-89018928-8269-4c85-9dba-c27ea85a56c8.mp4

### 你期望发生的行为？

正常导入

### 相关的崩溃日志 位于 `%HOMEPATH%/Documents/Hutao/Log.db`

```
System.ArgumentNullException: Value cannot be null. (Parameter 'dictionary')
   at System.Collections.Generic.CollectionExtensions.GetValueOrDefault[TKey,TValue](IReadOnlyDictionary`2 dictionary, TKey key, TValue defaultValue)
   at System.Collections.Generic.CollectionExtensions.GetValueOrDefault[TKey,TValue](IReadOnlyDictionary`2 dictionary, TKey key)
   at Snap.Hutao.Service.GachaLog.GachaLogService.GetItemId(GachaLogItem item)
   at Snap.Hutao.Service.GachaLog.GachaLogService.<>c__DisplayClass32_0.<ImportFromUIGF>b__4(UIGFItem i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityStates(IEnumerable`1 entities, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRange(IEnumerable`1 entities)
   at Snap.Hutao.Service.GachaLog.GachaLogService.ImportFromUIGF(List`1 list, String uid)
   at Snap.Hutao.Service.GachaLog.GachaLogService.<>c__DisplayClass28_0.<ImportFromUIGFAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Snap.Hutao.ViewModel.GachaLogViewModel.TryImportUIGFInternalAsync(UIGF uigf)
   at Snap.Hutao.ViewModel.GachaLogViewModel.TryImportUIGFInternalAsync(UIGF uigf)
   at Snap.Hutao.ViewModel.GachaLogViewModel.ImportFromUIGFJsonAsync()
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
```

### 我确认已在表单中附上了充足的补充说明以帮助开发人员确定问题

- [X] 是

### 我确认没有他人提出相同或类似的问题

- [X] 是

### 我确认该问题没有在文档中解释

- [X] 是

**Comment by WismyYao** [comment]
HuTao 1.1.14.0   也有同样的问题， 导入的祈愿记录不显示
