### ISSUE TITLE
[Bug]: 胡桃有概率在关闭后无法再次打开

### ISSUE THREAD

**Issue by hg429108** [DGP-Studio/Snap.Hutao#1266]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.2861

### Snap Hutao 版本

1.9.4.0

### 设备 ID

532BF9523FADAEBFCAC9F1F8324BA0C7

### 问题分类

安装和环境

### 发生了什么？

胡桃首次安装在原神4.3更新后，仅安装过1.9.1.0与1.9.4.0两个版本，因经常启动无反应而多次卸载重装，但无济于事。
正常关闭胡桃后，有一定概率无法再次启动胡桃，无论是否以管理员权限启动，均无反应。
并注意到在尝试启动胡桃无果后，Windows 事件查看器会刷新胡桃相关的错误报告，请查看相关附件。

[.NET Runtime.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13833813/default.NET.Runtime.txt)
[Application Error.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13833814/Application.Error.txt)
[Windows Error Reporting.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13833816/Windows.Error.Reporting.txt)
[Snap.Hutao Error Log.txt](https://github.com/DGP-Studio/Snap.Hutao/files/13833818/Snap.Hutao.Error.Log.txt)

日志名称:          Application
来源:            .NET Runtime
日期:            2024/1/5 1:34:32
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           HUAWEI-MateStation-X
描述:
Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at Snap.Hutao.Core.DependencyInjection.IocConfiguration.AddDbContextCore(IServiceProvider provider, DbContextOptionsBuilder builder) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\IocConfiguration.cs:line 48
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Service.Abstraction.DbStoreOptions.GetOption[T](T& storage, String key, Func`2 deserializer, T defaultValue) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\Abstraction\DbStoreOptions.cs:line 129
   at Snap.Hutao.Service.AppOptions.get_CurrentCulture() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\AppOptions.cs:line 41
   at Snap.Hutao.Core.DependencyInjection.DependencyInjection.Initialize() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\DependencyInjection.cs:line 43
   at Snap.Hutao.Program.Main(String[] args) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Program.cs:line 34

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2024-01-04T17:34:32.6236202Z" />
    <EventRecordID>16450</EventRecordID>
    <Correlation />
    <Execution ProcessID="13108" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>HUAWEI-MateStation-X</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at Snap.Hutao.Core.DependencyInjection.IocConfiguration.AddDbContextCore(IServiceProvider provider, DbContextOptionsBuilder builder) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\IocConfiguration.cs:line 48
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.&lt;&gt;c__DisplayClass17_0`1.&lt;AddCoreServices&gt;b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.&lt;&gt;c__DisplayClass2_0.&lt;RealizeService&gt;b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Service.Abstraction.DbStoreOptions.GetOption[T](T&amp; storage, String key, Func`2 deserializer, T defaultValue) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\Abstraction\DbStoreOptions.cs:line 129
   at Snap.Hutao.Service.AppOptions.get_CurrentCulture() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\AppOptions.cs:line 41
   at Snap.Hutao.Core.DependencyInjection.DependencyInjection.Initialize() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\DependencyInjection.cs:line 43
   at Snap.Hutao.Program.Main(String[] args) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Program.cs:line 34
</Data>
  </EventData>
</Event>

### 你期望发生的行为？

希望胡桃可以多次关闭后，仍能正常启动（无论是否以管理员权限）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
备份并删除 `%userprofile%/Hutao/Userdata.db`

**Comment by hg429108** [comment]
把Userdata.db备份、删掉，重启pc，重启胡桃。
在胡桃设置中点击“重新以管理员权限启动”或“切换语言”，然后窗口消失，又无法启动了，只有重启pc才能重启胡桃。
胡桃诊断工具给出的错误报告与Windows事件查看器类似，都是
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 10: 'disk I/O error'.

**Comment by hg429108** [comment]
经排查，系Windows安全中心——“病毒和威胁防护”设置——文件夹限制访问的开启，使得“user/文档”处于“在受保护的文件夹”中，导致胡桃无法访问该目录下的hutao文件夹，进而无法正常启动。
解决方案：关闭“文件夹限制访问”、或在「通过“文件夹限制访问”允许某个应用」中将胡桃添加为允许的应用。

**Comment by Lightczx** [comment]
你可以在胡桃的设置中更改用户数据路径
