### ISSUE TITLE
[Bug]:无法正常启动和下载资源

### ISSUE THREAD

**Issue by UPXAZXAD782** [DGP-Studio/Snap.Hutao#1289]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23H2

### Snap Hutao 版本

1.9.40

### 设备 ID

8A548D2A768E21A5060E250976AA5EBE

### 问题分类

安装和环境

### 发生了什么？

用powershell安装后打开在下载资源下载到ChapterIcon时卡住不动随后闪退重新打开后显示安装主界面随后卡住无响应然后闪退，重新卸载安装后问题依旧

Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Your machine id: 8A548D2A768E21A5060E250976AA5EBE

Time: 2024-01-11T02:11:11.5209719Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.23.53103
.NET Version: 8.0.0
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: __EFMigrationsHistory.MigrationId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Snap.Hutao.Core.DependencyInjection.IocConfiguration.AddDbContextCore(IServiceProvider provider, DbContextOptionsBuilder builder) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\IocConfiguration.cs:line 53
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Service.Abstraction.DbStoreOptions.GetOption[T](T& storage, String key, Func`2 deserializer, T defaultValue) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\Abstraction\DbStoreOptions.cs:line 129
   at Snap.Hutao.Service.AppOptions.get_CurrentCulture() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Service\AppOptions.cs:line 41
   at Snap.Hutao.Core.DependencyInjection.DependencyInjection.Initialize() in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\DependencyInjection.cs:line 43
   at Snap.Hutao.Program.Main(String[] args) in D:\appveyor\project\Snap.Hutao.Project-8lv5q0a6wynuymtn\src\Snap.Hutao\Snap.Hutao\Program.cs:line 34

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
删除 Userdata.db 不要尝试降版本使用胡桃
