### ISSUE TITLE
[Network]: 工具箱啟動即彈出404錯誤 

### ISSUE THREAD

**Issue by SSB-ARFCN** [DGP-Studio/Snap.Hutao#2030]
### 提交你的网络诊断报告

[SH-Report-41de194a-df22-4493-ad16-2b9f5f1f933a.zip](https://github.com/user-attachments/files/17292033/SH-Report-41de194a-df22-4493-ad16-2b9f5f1f933a.zip)

### 你的地理位置

臺灣

### 你的运营商

其它

### 你的问题

获取到了不正确的页面或数据

### 你的问题（补充）

網路運營商:台灣大哥大 (466-97) 手機: POCO F6 開啟WIFI熱點分享連線到電腦

![螢幕擷取畫面 (62)](https://github.com/user-attachments/assets/bf21c9c7-2225-4fa4-b031-9cfd057ebdb9)
今天下午開始啟動工具箱總是彈出404的對話方塊  首頁-活動公告資料未顯示 

2024-10-08 18:23:08.735 info: System.Net.Http.HttpClient.AnnouncementClient.LogicalHandler[101]
      End processing HTTP request after 530.7905ms - 404
2024-10-08 18:23:08.737 warn: Snap.Hutao.Web.Hoyolab.Hk4e.Common.Announcement.AnnouncementClient[0]
      ?求异常已忽略: https://hk4e-api-os.hoyoverse.com/common/hk4e_global/announcement/api/getAnnList?game=hk4e&game_biz=hk4e_global&lang=zh-tw&bundle_id=hk4e_global&platform=pc&region=os_asia&level=55&uid=100000000
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Snap.Hutao.Web.Request.Builder.HttpRequestMessageBuilderExtension.SendAsync[TResult](HttpRequestMessageBuilder builder, HttpClient httpClient, ILogger logger, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Web\Request\Builder\HttpRequestMessageBuilderExtension.cs:line 49

### 最后一步

- [X] 我已经在该议题中上传了包含网络诊断报告的加密压缩包

**Comment by SSB-ARFCN** [comment]
在嘗試切換公告所屬伺服器時發現 四個國際服選項都會彈出一樣的404對話方塊遊戲公告一樣無法顯示 而兩個陸服選項節能正常使用 
已暫時切換為陸服使用

**Comment by Mikachu2333** [comment]
修复中

**Comment by Mikachu2333** [comment]
https://sg-hk4e-api.hoyoverse.com/common/hk4e_global/announcement/api/getAnnList?game=hk4e&game_biz=hk4e_global&lang=zh-cn&bundle_id=hk4e_global&channel_id=1&level=24&platform=pc&region=os_cht&uid=100000000
