### ISSUE TITLE
[Bug]: 当我尝试更新我的 Snap Hutao 时产生报错

### ISSUE THREAD

**Issue by obuyniq** [DGP-Studio/Snap.Hutao#2099]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

10.0.22631.4317

### Snap Hutao 版本

1.11.6.0（更新后的版本）

### 设备 ID

FC51681A86EDC89E4BB66D498538887E

### 问题分类

安装和环境

### 发生了什么？

当我在试图更新 Snap Hutao 至 1.11.6.0 版本时，出现了以下报错：

```
Windows 10.0.22631.4317
System Architecture: X64
Process Architecture: X64
Framework: .NET 8.0.8

Exception Data:
----------------------------------------
System.ArgumentNullException: Value cannot be null. (Parameter 'reference.Window')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Snap.Hutao.Core.LifeCycle.CurrentXamlWindowReferenceExtension.GetXamlRoot(ICurrentXamlWindowReference reference) in C:\Users\Public\appveyor\Snap.Hutao-78xwnn2p82h7pewu\src\Snap.Hutao\Snap.Hutao\Core\LifeCycle\CurrentXamlWindowReferenceExtension.cs:line 14
   at Snap.Hutao.Factory.ContentDialog.ContentDialogFactory.CreateForConfirmCancelAsync(String title, String content, ContentDialogButton defaultButton) in C:\Users\Public\appveyor\Snap.Hutao-78xwnn2p82h7pewu\src\Snap.Hutao\Snap.Hutao\Factory\ContentDialog\ContentDialogFactory.cs:line 48
   at Snap.Hutao.ViewModel.TitleViewModel.DoCheckUpdateAsync() in C:\Users\Public\appveyor\Snap.Hutao-78xwnn2p82h7pewu\src\Snap.Hutao\Snap.Hutao\ViewModel\TitleViewModel.cs:line 125
   at Snap.Hutao.ViewModel.TitleViewModel.InitializeOverrideAsync() in C:\Users\Public\appveyor\Snap.Hutao-78xwnn2p82h7pewu\src\Snap.Hutao\Snap.Hutao\ViewModel\TitleViewModel.cs:line 69
   at Snap.Hutao.ViewModel.Abstraction.ViewModel.InitializeAsync() in C:\Users\Public\appveyor\Snap.Hutao-78xwnn2p82h7pewu\src\Snap.Hutao\Snap.Hutao\ViewModel\Abstraction\ViewModel.cs:line 48
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

然后退出并再次启动 Snap Hutao，就成功更新了

### 你期望发生的行为？

不产生报错

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
你过早的关闭了主窗口
