### ISSUE TITLE
[Bug]: 网页缓存更新抽卡记录出现BUG

### ISSUE THREAD

**Issue by CJDHawk** [DGP-Studio/Snap.Hutao#2103]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4391

### Snap Hutao 版本

1.11.6.0

### 设备 ID

782866F201821D4AE5D487FB12E6387E

### 问题分类

祈愿记录

### 发生了什么？

当尝试使用网页缓存来更新抽卡记录的时候，APP闪退并且弹出以下错误

Windows 10.0.22631.4391
System Architecture: X64
Process Architecture: X64
Framework: .NET 8.0.10

Exception Data:
----------------------------------------
System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\miHoYo Launcher\games\Genshin Impact Game\YuanShen_Data\webCaches\2.30.0.0\Cache\Cache_Data\data_2' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at Snap.Hutao.Service.GachaLog.QueryProvider.GachaLogQueryWebCacheProvider.GetQueryAsync() in C:\Users\Public\appveyor\Snap.Hutao-9ccf084dxwbrv3ml\src\Snap.Hutao\Snap.Hutao\Service\GachaLog\QueryProvider\GachaLogQueryWebCacheProvider.cs:line 64
   at Snap.Hutao.ViewModel.GachaLog.GachaLogViewModel.RefreshCoreAsync(RefreshOption option) in C:\Users\Public\appveyor\Snap.Hutao-9ccf084dxwbrv3ml\src\Snap.Hutao\Snap.Hutao\ViewModel\GachaLog\GachaLogViewModel.cs:line 150
   at Snap.Hutao.ViewModel.GachaLog.GachaLogViewModel.RefreshByWebCacheAsync() in C:\Users\Public\appveyor\Snap.Hutao-9ccf084dxwbrv3ml\src\Snap.Hutao\Snap.Hutao\ViewModel\GachaLog\GachaLogViewModel.cs:line 132
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2083
