### ISSUE TITLE
[Bug]: 更新1.11.8.0后无法启动程序

### ISSUE THREAD

**Issue by miravois** [DGP-Studio/Snap.Hutao#2136]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.8.0

### 设备 ID

9140C456A4557FC8325C1D884F1396C6

### 问题分类

游戏启动器

### 发生了什么？

**编辑：**
已尝试卸载并重新安装启动1.11.8.0，一样会崩溃。
尝试安装启动1.11.7.0也会崩溃。
1.11.6.0可以正常打开。问题应该出在1.11.7.0上。

**原文：**
在更新1.11.8.0之前一切正常，我能正常启动程序，也能启动原神。
在更新1.11.8.0（胡桃内弹窗提示更新）后，程序一打开就崩溃，弹窗内显示如下错误：

Snap Hutao 1.11.8.0
Windows 10.0.19045.5011
System Architecture: X64
Process Architecture: X64
Framework: .NET 8.0.10

Exception Data:
----------------------------------------
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Snap.Hutao.Service.Cultivation.CultivationService.EnsureCurrentProjectAsync() in C:\Users\Public\appveyor\Snap.Hutao-pae07j2s3mjj4pau\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationService.cs:line 237
   at Snap.Hutao.Service.Cultivation.CultivationServiceExtension.GetCultivateEntryCollectionForCurrentProjectAsync(ICultivationService cultivationService, ICultivationMetadataContext context) in C:\Users\Public\appveyor\Snap.Hutao-pae07j2s3mjj4pau\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationServiceExtension.cs:line 14
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.CreateWeekDays() in C:\Users\Public\appveyor\Snap.Hutao-pae07j2s3mjj4pau\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 162
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-pae07j2s3mjj4pau\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 48
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

运行诊断工具得到的错误信息：

Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Windows version: 10.0.19045.5011
Public IP: 70.52.180.59
Your machine id: 9140C456A4557FC8325C1D884F1396C6

Time: 2024-07-31T00:29:05.2382328Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at Snap.Hutao.Service.Discord.DiscordController+DiscordUpdateActivityAsyncAction.HandleResult(Void*, Snap.Discord.GameSDK.ABI.DiscordResult)
   at Snap.Hutao.Service.Discord.DiscordController+<DiscordRunCallbacksAsync>d__13.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1[[System.Boolean, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SignalCompletion()
   at System.Threading.PeriodicTimer+State.Signal(Boolean, System.Threading.CancellationToken)
   at System.Threading.TimerQueueTimer.Fire(Boolean)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

### 你期望发生的行为？

能正常启动程序。

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
把你Userdata.db发一下

**Comment by miravois** [comment]
[Userdata.db.txt](https://github.com/user-attachments/files/17628241/Userdata.db.txt)

**Comment by Lightczx** [comment]
[Userdata.zip](https://github.com/user-attachments/files/17628290/Userdata.zip)
替换一下

**Comment by miravois** [comment]
升级到最新也能正常打开了，谢谢！
