### ISSUE TITLE
[Bug]: 更新到最新版本后一打开软件就崩溃

### ISSUE THREAD

**Issue by q471240142** [DGP-Studio/Snap.Hutao#2148]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5011

### Snap Hutao 版本

1.11.9.0

### 设备 ID

B356783FED10C62BF30A6273A8D5B7B6

### 问题分类

用户界面

### 发生了什么？

更新最新版后打开软件就奔溃，卸载了从新安装也不行。
 ![Image](https://github.com/user-attachments/assets/a0ae723b-e143-45c9-8eb0-ac5a921a5807)
[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17690309/Snap.Hutao.Error.Log.txt)

Snap Hutao 1.11.9.0
Windows 10.0.19045.5011
System Architecture: X64
Process Architecture: X64
Framework: .NET 8.0.8

Exception Data:
----------------------------------------
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Snap.Hutao.Service.Cultivation.CultivationService.EnsureCurrentProjectAsync() in C:\Users\Public\appveyor\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationService.cs:line 237
   at Snap.Hutao.Service.Cultivation.CultivationServiceExtension.GetCultivateEntryCollectionForCurrentProjectAsync(ICultivationService cultivationService, ICultivationMetadataContext context) in C:\Users\Public\appveyor\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationServiceExtension.cs:line 14
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.CreateWeekDays() in C:\Users\Public\appveyor\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 162
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 48
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
![Image](https://github.com/user-attachments/assets/d50c3959-226e-487a-a472-011548b7aac3)

### 最后一步

- [ ] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by qhy040404** [comment]
加群找管理私发Userdata,db

**Comment by q471240142** [comment]
[Userdata.zip](https://github.com/user-attachments/files/17700845/Userdata.zip)

**Comment by q471240142** [comment]
> 加群找管理私发Userdata，db



> 加群找管理私发Userdata,db

[Userdata.zip](https://github.com/user-attachments/files/17700876/Userdata.zip)
 是这个吗？

**Comment by qhy040404** [comment]
[Userdata.zip](https://github.com/user-attachments/files/17701352/Userdata.zip)
覆盖回去

**Comment by q471240142** [comment]
> [Userdata.zip](https://github.com/user-attachments/files/17701352/Userdata.zip) 覆盖回去

谢谢大佬帮我搞好

**Comment by y-love-t** [comment]
同样遇到这个问题，如何加群

**Comment by q471240142** [comment]
567908135  Q群



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月17日(星期天) 下午2:55
收件人: "DGP-Studio/Snap.Hutao";
抄送: "Author";
主题: Re: [DGP-Studio/Snap.Hutao] [Bug]: 更新到最新版本后一打开软件就崩溃 (Issue #2148)





 
同样遇到这个问题，如何加群
 
&mdash;
