### ISSUE TITLE
[Bug]: 启动后不久就弹出致命错误

### ISSUE THREAD

**Issue by Latomoyocarl** [DGP-Studio/Snap.Hutao#2163]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5073

### Snap Hutao 版本

1.12.1.0

### 设备 ID

CDBAE21A62486FEC7319FBBCFFAFAD64

### 问题分类

游戏启动器

### 发生了什么？

启动后不久，米游社账号自动登陆之前，且便签加载出来之前，就连续弹出两个致命错误的窗口，内容如下

```
Snap Hutao 1.12.1.0
Windows 10.0.19045.5131
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.Text.Json.JsonException: JSON deserialization for type 'Snap.Hutao.Model.Metadata.Avatar.ProfilePicture' was missing required properties including: 'Name'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrSingleFile[T](MetadataFileStrategy strategy, String cacheKey, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 89
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrFileAsync[T](MetadataFileStrategy strategy, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 72
   at Snap.Hutao.Service.Metadata.ContextAbstraction.MetadataServiceContextExtension.GetContextAsync[TContext](IMetadataService metadataService, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\ContextAbstraction\MetadataServiceContextExtension.cs:line 55
   at Snap.Hutao.Service.User.ProfilePictureService.TryUpdateUserGameRoleAsync(UserGameRole userGameRole, UidProfilePicture cache, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\ProfilePictureService.cs:line 82
   at Snap.Hutao.Service.User.ProfilePictureService.TryInitializeAsync(User user, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\ProfilePictureService.cs:line 31
   at Snap.Hutao.Service.User.UserInitializationService.InitializeUserAsync(User user, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\UserInitializationService.cs:line 198
   at Snap.Hutao.Service.User.UserInitializationService.ResumeUserAsync(User inner, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\UserInitializationService.cs:line 28
   at Snap.Hutao.Extension.ListExtension.SelectListAsync[TSource,TResult](List`1 list, Func`3 selector, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Extension\ListExtension.cs:line 157
   at Snap.Hutao.Service.User.UserCollectionService.GetUsersAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\UserCollectionService.cs:line 36
   at Snap.Hutao.Service.User.UserServiceExtension.GetUserGameRoleByUidAsync(IUserService userService, String uid) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\User\UserServiceExtension.cs:line 21
   at Snap.Hutao.Service.DailyNote.DailyNoteService.GetDailyNoteEntryCollectionAsync(Boolean forceRefresh, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\DailyNote\DailyNoteService.cs:line 94
   at Snap.Hutao.ViewModel.DailyNote.DailyNoteViewModelSlim.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\DailyNote\DailyNoteViewModelSlim.cs:line 42
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

### 你期望发生的行为？

正常使用

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@Latomoyocarl 你的界面语言是什么

**Comment by Latomoyocarl** [comment]
> [@Latomoyocarl](https://github.com/Latomoyocarl) 你的界面语言是什么

日语，更新时忘记切回汉语了

**Comment by Lightczx** [comment]
过一会更新完元数据就行了
