### ISSUE TITLE
[Bug]: 更新1.12.1.0版本无法启动

### ISSUE THREAD

**Issue by streesobrs** [DGP-Studio/Snap.Hutao#2165]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.2728

### Snap Hutao 版本

1.12.1.0

### 设备 ID

A2CEED24354BDF0FDED35AB76A4A0633

### 问题分类

其它

### 发生了什么？

更新完后界面打不开
下面是诊断工具的内容

Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Windows version: 10.0.19045.2728
Public IP: 125.84.65.64
Your machine id: A2CEED24354BDF0FDED35AB76A4A0633

Time: 2024-03-23T15:23:31.0841385Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ABI.Microsoft.UI.Xaml.IFrameworkElementMethods.set_DataContext(WinRT.IObjectReference, System.Object)
   at Microsoft.UI.Xaml.FrameworkElement.set_DataContext(System.Object)
   at Snap.Hutao.Control.ScopedPage.OnUnloaded(System.Object, Microsoft.UI.Xaml.RoutedEventArgs)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr, IntPtr, IntPtr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Snap.Hutao.Program.Main(System.String[])

Time: 2024-03-22T11:59:26.4202959Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.324.11423
.NET Version: 8.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at ABI.Microsoft.UI.Xaml.IFrameworkElementMethods.set_DataContext(WinRT.IObjectReference, System.Object)
   at Microsoft.UI.Xaml.FrameworkElement.set_DataContext(System.Object)
   at Snap.Hutao.Control.ScopedPage.OnUnloaded(System.Object, Microsoft.UI.Xaml.RoutedEventArgs)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr, IntPtr, IntPtr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Snap.Hutao.Program.Main(System.String[])

Time: 2024-02-12T14:54:23.4214364Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 14c9ba2525ad1c12

TraceId: 7aca20cbe3fcb2dc2c574516b71dd4d4

ParentId: 0000000000000000

ConnectionId: 0HN1BORNO57A5

RequestId: 0HN1BORNO57A5:00000001

RequestPath: /DGP-Studio/Snap.Hutao

GET https://github.com/DGP-Studio/Snap.Hutao responded 502 in 10574.3893 ms

System.Threading.Tasks.TaskCanceledException: A task was canceled.

Time: 2024-01-30T06:25:10.6436696Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 8d3d51a22985c9d8

TraceId: f7905774c3992f099d2a33e7cba23420

ParentId: 0000000000000000

ConnectionId: 0HN11BFJF81DO

RequestId: 0HN11BFJF81DO:0000000F

RequestPath: /DGP-Studio/Snap.Hutao/actions

GET https://github.com/DGP-Studio/Snap.Hutao/actions responded 502 in 17769.3102 ms

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.

System.Net.Sockets.SocketException: 由于线程退出或应用程序请求，已中止 I/O 操作。

Time: 2024-01-30T06:24:50.4677768Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: bda5432049575450

TraceId: 7f8a8f1a0ffbe744ce651dc51e58ae5b

ParentId: 0000000000000000

ConnectionId: 0HN11BFJF81DO

RequestId: 0HN11BFJF81DO:0000000B

RequestPath: /DGP-Studio/Snap.Hutao/actions/runs/7707052335/job/21003604496

GET https://github.com/DGP-Studio/Snap.Hutao/actions/runs/7707052335/job/21003604496 responded 502 in 1319.0305 ms

System.Threading.Tasks.TaskCanceledException: A task was canceled.

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by galeondx** [comment]
同上 打開後跳兩個錯誤框重新安裝跟刪除data都一樣

```
Snap Hutao 1.12.1.0
Windows 10.0.19045.5131
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.Text.Json.JsonException: JSON deserialization for type 'Snap.Hutao.Model.Metadata.Avatar.ProudableSkill' was missing required properties including: 'Name', 'Description'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrScatteredFile[T](MetadataFileStrategy strategy, String cacheKey, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 109
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrFileAsync[T](MetadataFileStrategy strategy, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 72
   at Snap.Hutao.Service.Metadata.ContextAbstraction.MetadataServiceContextExtension.GetContextAsync[TContext](IMetadataService metadataService, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\ContextAbstraction\MetadataServiceContextExtension.cs:line 30
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.CreateWeekDays() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 145
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by galeondx** [comment]
```
Snap Hutao 1.12.1.0
Windows 10.0.19045.5131
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.Text.Json.JsonException: JSON deserialization for type 'Snap.Hutao.Model.Metadata.Avatar.ProudableSkill' was missing required properties including: 'Name', 'Description'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrScatteredFile[T](MetadataFileStrategy strategy, String cacheKey, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 109
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrFileAsync[T](MetadataFileStrategy strategy, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 72
   at Snap.Hutao.Service.Metadata.ContextAbstraction.MetadataServiceContextExtension.GetContextAsync[TContext](IMetadataService metadataService, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\ContextAbstraction\MetadataServiceContextExtension.cs:line 30
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.CreateWeekDays() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 145
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

**Comment by Lightczx** [comment]
不同语言下的无法启动问题不要发在同一个Issue里面，此issue作废
