### ISSUE TITLE
[Bug]: 遇到了無法修復的致命錯誤

### ISSUE THREAD

**Issue by RJFAC** [DGP-Studio/Snap.Hutao#2167]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22000.3260

### Snap Hutao 版本

1.12.1.0

### 设备 ID

4B263104B9BECC724DFC70A8EEA7F25A

### 问题分类

实时便笺

### 发生了什么？

Snap Hutao 1.12.1.0
Windows 10.0.22000.3260
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.Text.Json.JsonException: JSON deserialization for type 'Snap.Hutao.Model.Metadata.Avatar.ProudableSkill' was missing required properties including: 'Name', 'Description'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrScatteredFile[T](MetadataFileStrategy strategy, String cacheKey, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 109
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrFileAsync[T](MetadataFileStrategy strategy, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 72
   at Snap.Hutao.Service.Metadata.MetadataServiceImmutableDictionaryExtension.<>c__DisplayClass23_0`2.<<FromCacheAsDictionaryAsync>b__0>d.MoveNext() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataServiceImmutableDictionaryExtension.cs:line 240
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory, MemoryCacheEntryOptions createOptions)
   at Snap.Hutao.Service.Metadata.MetadataServiceImmutableDictionaryExtension.FromCacheAsDictionaryAsync[TKey,TValue](IMetadataService metadataService, MetadataFileStrategy strategy, Func`2 keySelector, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataServiceImmutableDictionaryExtension.cs:line 238
   at Snap.Hutao.Service.Metadata.ContextAbstraction.MetadataServiceContextExtension.GetContextAsync[TContext](IMetadataService metadataService, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Metadata\ContextAbstraction\MetadataServiceContextExtension.cs:line 83
   at Snap.Hutao.Service.GachaLog.GachaLogService.InitializeAsync(CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\GachaLog\GachaLogService.cs:line 48
   at Snap.Hutao.ViewModel.GachaLog.GachaLogViewModel.LoadOverrideAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\GachaLog\GachaLogViewModel.cs:line 79
   at Snap.Hutao.ViewModel.Abstraction.ViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Abstraction\ViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 你期望发生的行为？

切換分頁後胡桃啟動器彈出錯誤並閃退
使用環境為國際服

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2166
