### ISSUE TITLE
[Bug]: 刷新幻想真境剧诗数据失败并使得程序崩溃

### ISSUE THREAD

**Issue by zbh531** [DGP-Studio/Snap.Hutao#2170]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.4460

### Snap Hutao 版本

1.12.1.0

### 设备 ID

35E9E5DC6A07AF5DB231204D2EC9B7BD

### 问题分类

其它

### 发生了什么？

使用的Snap Hutao是英文界面，国际服原神。

点击幻想真境剧诗的“Refresh Data”后，程序崩溃闪退，并跳出以下错误窗口。再次打开后，发现刷新并未成功，再次点击“Refresh Data”后依旧使得程序崩溃。

![Image](https://github.com/user-attachments/assets/67e17596-af41-4cbc-8a13-833143d4d17f)

### 你期望发生的行为？

能够刷新数据

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by BTMuli** [comment]
目前所有的国际服功能支持均由社区贡献，在国际服无法使用某些功能时我们仅提供有限的支持。
如果有人愿意贡献修复这些功能的代码，非常欢迎对 develop 分支发起 PR。

Currently, all Hoyoverse/HoYoLAB feature support is contributed by the community, and we only provide limited support when some features are not available on the it.
If anyone would like to contribute code that fixes these features, a PR to the develop branch is more than welcome.

**Comment by sheaahhoi1** [comment]
Snap Hutao 1.12.1.0
Windows 10.0.26100.2152
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.NotSupportedException: Specified method is not supported.
   at Snap.Hutao.Web.Hutao.RoleCombat.HutaoRoleCombatClient.GetPlayerRecordAsync(UserAndUid userAndUid, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Web\Hutao\RoleCombat\HutaoRoleCombatClient.cs:line 57
   at Snap.Hutao.ViewModel.RoleCombat.RoleCombatViewModel.UploadRoleCombatRecordAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\RoleCombat\RoleCombatViewModel.cs:line 119
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

**Comment by qhy040404** [comment]
@zbh531 @sheaahhoi1 麻烦测试一下这个版本，应该可以正常获取了。 https://github.com/DGP-Studio/Snap.Hutao/actions/runs/11891306674

**Comment by zbh531** [comment]
成功了！感谢！

![Image](https://github.com/user-attachments/assets/1656b120-2cf5-4ed8-a299-d954e833b097)
