### ISSUE TITLE
[Bug]: 遇到了无法恢复的致命错误

### ISSUE THREAD

**Issue by Taudons** [DGP-Studio/Snap.Hutao#2174]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.5131

### Snap Hutao 版本

1.12.1.0

### 设备 ID

929600184D3EAE19B08B287B312AA628

### 问题分类

游戏启动器

### 发生了什么？

打开胡桃后卡在主界面无法操作，一两秒后就闪退报错
环境是官服简中
之前老版本的时候闪退报错，
更新最新版本或者卸载重下后还是闪退报错

Snap Hutao 1.12.1.0
Windows 10.0.19045.5131
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Snap.Hutao.Service.Cultivation.CultivationService.EnsureCurrentProjectAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationService.cs:line 237
   at Snap.Hutao.Service.Cultivation.CultivationServiceExtension.GetCultivateEntryCollectionForCurrentProjectAsync(ICultivationService cultivationService, ICultivationMetadataContext context) in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\Service\Cultivation\CultivationServiceExtension.cs:line 13
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.CreateWeekDays() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 160
   at Snap.Hutao.ViewModel.Calendar.CalendarViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-0vfibuvt4r4cnpja\src\Snap.Hutao\Snap.Hutao\ViewModel\Calendar\CalendarViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by twjmy** [comment]
我也有同样的问题，重下安装 1.12.0 以及 1.12.1 都会有这个问题。
目前是下回 [1.11.9 版本](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.11.9)
