### ISSUE TITLE
[Bug]: 遇到了无法恢复的致命错误

### ISSUE THREAD

**Issue by DMZ20010102** [DGP-Studio/Snap.Hutao#2200]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

26100.2314

### Snap Hutao 版本

1.12.2.0

### 设备 ID

0B949BB4E2921772566F2177F0DF5EE9

### 问题分类

安装和环境

### 发生了什么？

打开胡桃时可以正常启动，
进入程序后发现各种模块不加载
![Image](https://github.com/user-attachments/assets/386d753d-4754-4079-96d6-504227dacade)
退出胡桃后发现遇到无法恢复的致命错误
![Image](https://github.com/user-attachments/assets/e0383b26-d6ad-4146-81a6-29fa255b09b5)
下方是Snap.Hutao Error Log.txt以及报错信息
[Snap.Hutao Error Log.txt](https://github.com/user-attachments/files/17830506/Snap.Hutao.Error.Log.txt)
Snap Hutao 1.12.2.0
Windows 10.0.26100.2314
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
----------------------------------------
System.Runtime.InteropServices.COMException (0x80070582): 类已存在。 (0x80070582)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Snap.Hutao.UI.Shell.NotifyIconMessageWindow..ctor() in C:\Users\Public\appveyor\Snap.Hutao-b0gle226p0dq575m\src\Snap.Hutao\Snap.Hutao\UI\Shell\NotifyIconMessageWindow.cs:line 46
   at Snap.Hutao.UI.Shell.NotifyIconController..ctor(IServiceProvider serviceProvider) in C:\Users\Public\appveyor\Snap.Hutao-b0gle226p0dq575m\src\Snap.Hutao\Snap.Hutao\UI\Shell\NotifyIconController.cs:line 38
   at InvokeStub_NotifyIconController..ctor(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.UI.Windowing.XamlWindowController.IsNotifyIconVisible() in C:\Users\Public\appveyor\Snap.Hutao-b0gle226p0dq575m\src\Snap.Hutao\Snap.Hutao\UI\Windowing\XamlWindowController.cs:line 159
   at Snap.Hutao.UI.Windowing.XamlWindowController.OnWindowClosed(Object sender, WindowEventArgs args) in C:\Users\Public\appveyor\Snap.Hutao-b0gle226p0dq575m\src\Snap.Hutao\Snap.Hutao\UI\Windowing\XamlWindowController.cs:line 124
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_object__global__Microsoft_UI_Xaml_WindowEventArgs_.EventState.<GetEventInvoke>b__1_0(Object sender, WindowEventArgs args)
   at WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_object__Microsoft_UI_Xaml_WindowEventArgs.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr args)

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2198
