### ISSUE TITLE
[Bug]: 启动器无法启动

### ISSUE THREAD

**Issue by cunx413** [DGP-Studio/Snap.Hutao#2225]
### 检查清单

- [x] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [x] 我知道[文档站](https://hut.ao/zh/menu.html)的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [x] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

19045.1826

### Snap Hutao 版本

1.12.3.0

### 设备 ID

FECE131E13D2928FA9AA24E4D022CEA2

### 问题分类

安装和环境

### 发生了什么？

Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Windows version: 10.0.19045.1826
Public IP: 111.15.176.111
Your machine id: FECE131E13D2928FA9AA24E4D022CEA2

Time: 2024-05-10T23:15:58.0070253Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Object, System.Span`1<System.Object>, System.Reflection.BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at WinRT.DelegateExtensions.DynamicInvokeAbi(System.Delegate, System.Object[])
   at ABI.Windows.Foundation.Collections.IMapMethods`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].HasKey(WinRT.IObjectReference, System.__Canon)
   at ABI.System.Collections.Generic.IDictionaryMethods`2[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ContainsKey(WinRT.IObjectReference, System.__Canon)
   at Microsoft.UI.Xaml.ResourceDictionary.ContainsKey(System.Object)
   at Snap.Hutao.View.InfoBarView+InfoBarView_obj1_Bindings.LookupConverter(System.String)
   at Snap.Hutao.View.InfoBarView+InfoBarView_obj1_Bindings.Update_InfoBars_Count(Int32, Int32)
   at Snap.Hutao.View.InfoBarView+InfoBarView_obj1_Bindings+InfoBarView_obj1_BindingsTracking.PropertyChanged_InfoBars(System.Object, System.ComponentModel.PropertyChangedEventArgs)
   at System.Collections.ObjectModel.ObservableCollection`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].RemoveItem(Int32)
   at System.Collections.ObjectModel.Collection`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Remove(System.__Canon)
   at Snap.Hutao.Service.Notification.InfoBarService+<PrepareInfoBarAndShowCoreAsync>d__8.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Snap.Hutao.Service.Notification.InfoBarService+<PrepareInfoBarAndShowCoreAsync>d__8, Snap.Hutao, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Snap.Hutao.Service.Notification.InfoBarService+<PrepareInfoBarAndShowCoreAsync>d__8, Snap.Hutao, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Snap.Hutao.Service.Notification.InfoBarService+<PrepareInfoBarAndShowCoreAsync>d__8, Snap.Hutao, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext+<>c__DisplayClass2_0.<Post>b__0()
   at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Snap.Hutao.Program.Main(System.String[])

Time: 2024-05-03T06:20:17.7671995Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.224.6711
.NET Version: 8.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DivideByZeroException: Attempted to divide by zero.   at WinRT.IObjectReference.DisposeTrackerSource()   at WinRT.IObjectReference.Dispose(Boolean disposing)   at WinRT.IObjectReference.Finalize()

更新之后，无法启动胡桃工具箱，点exe程序后，胡桃工具箱在任务管理器出现后，快速消失。无法启动。

### 你期望发生的行为？

希望能启动

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by cunx413** [comment]
![Image](https://github.com/user-attachments/assets/6a507343-8525-4513-8457-f71d6781658c)
启动后无反应（删除原文件，重新下载结果如图）
