### ISSUE TITLE
[Bug]: 遇到了无法恢复的致命错误

### ISSUE THREAD

**Issue by Seeridia** [DGP-Studio/Snap.Hutao#2240]
### Windows 版本

27754.1000

### Snap Hutao 版本

1.12.4.0

### 设备 ID

98C20035CC4D682D75C5332E2515A91A

### 问题分类

安装和环境

### 发生了什么？

程序打开后过数秒闪退，之后跳出两个相同的窗口提示 遇到了无法恢复的致命错误

重装不能解决问题

Snap Hutao 1.12.4.0
Windows 10.0.27754.1000
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
[string]:FileName:Avatar/10000002 - 副本
----------------------------------------
System.Text.Json.JsonException: JSON deserialization for type 'Snap.Hutao.Model.Metadata.Avatar.Avatar' was missing required properties including: 'NameCard'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, T& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrScatteredFile[T](MetadataFileStrategy strategy, String cacheKey, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 119
   at Snap.Hutao.Service.Metadata.MetadataService.FromCacheOrFileAsync[T](MetadataFileStrategy strategy, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataService.cs:line 72
   at Snap.Hutao.Service.Metadata.MetadataServiceImmutableDictionaryExtension.<>c__DisplayClass23_0`2.<<FromCacheAsDictionaryAsync>b__0>d.MoveNext() in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataServiceImmutableDictionaryExtension.cs:line 240
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory, MemoryCacheEntryOptions createOptions)
   at Snap.Hutao.Service.Metadata.MetadataServiceImmutableDictionaryExtension.FromCacheAsDictionaryAsync[TKey,TValue](IMetadataService metadataService, MetadataFileStrategy strategy, Func`2 keySelector, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\Metadata\MetadataServiceImmutableDictionaryExtension.cs:line 238
   at Snap.Hutao.Service.Metadata.ContextAbstraction.MetadataServiceContextExtension.GetContextAsync[TContext](IMetadataService metadataService, CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\Metadata\ContextAbstraction\MetadataServiceContextExtension.cs:line 83
   at Snap.Hutao.Service.GachaLog.GachaLogService.InitializeAsync(CancellationToken token) in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\Service\GachaLog\GachaLogService.cs:line 48
   at Snap.Hutao.ViewModel.GachaLog.GachaLogViewModelSlim.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-c53280n3iveyayo5\src\Snap.Hutao\Snap.Hutao\ViewModel\GachaLog\GachaLogViewModelSlim.cs:line 25
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
@qhy040404 Metadata loading behavior can be changed to avoid this issue
