### ISSUE TITLE
[Bug]: 运行一段时间后崩溃，并提示【遇到了无法恢复的致命错误】

### ISSUE THREAD

**Issue by Tiamat9527** [DGP-Studio/Snap.Hutao#2270]
### Windows 版本

Windows 10.0.19045.5198

### Snap Hutao 版本

Snap Hutao 1.12.5.0

### 设备 ID

96E3A4187FD1BDD87662E2262DBDE7FC

### 问题分类

安装和环境

### 发生了什么？

【以下是崩溃窗口内容】
```
Snap Hutao 1.12.5.0
Windows 10.0.19045.5198
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
[string]:Description:组件初始化失败。

[string]:RestrictedDescription:System.Runtime.InteropServices.COMException
[string]:RestrictedErrorReference:
[string]:RestrictedCapabilitySid:
[WinRT.ObjectReferenceWithContext<WinRT.Interop.IUnknownVftbl>]:__RestrictedErrorObjectReference:WinRT.ObjectReferenceWithContext`1[WinRT.Interop.IUnknownVftbl]
[bool]:__HasRestrictedLanguageErrorObject:False
----------------------------------------
System.Runtime.InteropServices.COMException (0x80004005)
```
【以下是胡桃诊断工具log】
```
Generated by Snap Hutao Diagnosis Tool
--------------------------------------
Windows version: 10.0.19045.5198
Public IP: 124.235.164.11
Your machine id: 96E3A4187FD1BDD87662E2262DBDE7FC

Time: 2024-12-08T23:49:51.3857746Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 6bd624579a9365a5

TraceId: bb649a998298ed8ced67b387cd37f696

ParentId: 0000000000000000

ConnectionId: 0HN8G1BI52RBU

RequestId: 0HN8G1BI52RBU:00000002

RequestPath: /DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix



GET https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix responded 502 in 10380.7271 ms

System.Threading.Tasks.TaskCanceledException: The operation was canceled.

System.IO.IOException: Unable to read data from the transport connection: 由于线程退出或应用程序请求，已中止 I/O 操作。.

System.Net.Sockets.SocketException: 由于线程退出或应用程序请求，已中止 I/O 操作。





Time: 2024-12-08T23:49:51.3847745Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 06a809a37bbaa057

TraceId: 7ffd59af872addb6cd48b7ecf19e2566

ParentId: 0000000000000000

ConnectionId: 0HN8G1BI52RC1

RequestId: 0HN8G1BI52RC1:00000002

RequestPath: /DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix



GET https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix responded 502 in 10378.381 ms

System.Threading.Tasks.TaskCanceledException: A task was canceled.





Time: 2024-12-08T23:49:51.3847745Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 5b3ab7911f006596

TraceId: e994534a9ac6b346bd06983b96faa656

ParentId: 0000000000000000

ConnectionId: 0HN8G1BI52RBV

RequestId: 0HN8G1BI52RBV:00000002

RequestPath: /DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix



GET https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix responded 502 in 10378.1383 ms

System.Threading.Tasks.TaskCanceledException: A task was canceled.





Time: 2024-12-08T23:49:51.3837745Z
EventData: Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware

EventId: 0

SpanId: 05db8004998f1d45

TraceId: 568f0202ff05483e3d145e33d8ae676c

ParentId: 0000000000000000

ConnectionId: 0HN8G1BI52RC0

RequestId: 0HN8G1BI52RC0:00000002

RequestPath: /DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix


GET https://github.com/DGP-Studio/Snap.Hutao/releases/download/1.12.5/Snap.Hutao.1.12.5.msix responded 502 in 10378.0929 ms

System.Threading.Tasks.TaskCanceledException: A task was canceled.



Time: 2024-11-26T04:08:05.7852804Z
EventData: Application: Snap.Hutao.exe
CoreCLR Version: 8.0.824.36612
.NET Version: 8.0.8
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at WinRT.Interop.Platform.CoGetContextToken(IntPtr*)
   at WinRT.Interop.Platform.CoGetContextToken(IntPtr*)
   at ABI.System.ComponentModel.PropertyChangedEventHandler+NativeDelegateWrapper.Invoke(System.Object, System.ComponentModel.PropertyChangedEventArgs)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.OnPropertyChanged(System.String)
   at CommunityToolkit.Mvvm.ComponentModel.ObservableObject.SetProperty[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.__Canon, System.String)
   at Snap.Hutao.ViewModel.Abstraction.ViewModel.SetProperty[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.__Canon, System.String)
   at Snap.Hutao.ViewModel.TitleViewModel.set_UpdateStatus(Snap.Hutao.Service.Update.UpdateStatus)
   at Snap.Hutao.ViewModel.TitleViewModel.<DoCheckUpdateAsync>b__20_0(Snap.Hutao.Service.Update.UpdateStatus)
   at Snap.Hutao.Factory.Progress.DispatcherQueueProgress`1+<>c__DisplayClass3_0[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<Report>b__0()
   at ABI.Microsoft.UI.Dispatching.DispatcherQueueHandler.Do_Abi_Invoke(IntPtr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start(WinRT.IObjectReference, Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Microsoft.UI.Xaml.Application.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback)
   at Snap.Hutao.Bootstrap.Main(System.String[])
```
【以下是事件查看器.net错误信息】
```
[常规]：
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 13
SpanId: 34cf49ed4058c276
TraceId: 17235f0d2f55b21a13520e3b21e31562
ParentId: 0000000000000000
ConnectionId: 0HN8G1BI52RCL
RequestId: 0HN8G1BI52RCL:00000002
RequestPath: /

Connection id "0HN8G1BI52RCL", Request id "0HN8G1BI52RCL:00000002": An unhandled exception was thrown by the application.

Exception: 
DnsClient.DnsResponseException: Query 18890 => hub5p.sandai.net:80 IN A on 182.254.116.116:53 timed out or is a transient error.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.Tasks.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken)
   at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+MoveNext()
   at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 130
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 132
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Core|91_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 30
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

[详细信息]
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?template=CHS-bug-report.yml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?template=CHS-bug-report.yml#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-12-08T23:50:25.3835970Z" /> 
  <EventRecordID>1855</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>Tiamat</Computer> 
  <Security /> 
  </System>
[-](https://github.com/DGP-Studio/Snap.Hutao/issues/new?template=CHS-bug-report.yml#) <EventData>
  <Data>Category: Microsoft.AspNetCore.Server.Kestrel EventId: 13 SpanId: 34cf49ed4058c276 TraceId: 17235f0d2f55b21a13520e3b21e31562 ParentId: 0000000000000000 ConnectionId: 0HN8G1BI52RCL RequestId: 0HN8G1BI52RCL:00000002 RequestPath: / Connection id "0HN8G1BI52RCL", Request id "0HN8G1BI52RCL:00000002": An unhandled exception was thrown by the application. Exception: DnsClient.DnsResponseException: Query 18890 => hub5p.sandai.net:80 IN A on 182.254.116.116:53 timed out or is a transient error. ---> System.OperationCanceledException: The operation was canceled. at System.Threading.Tasks.TaskExtensions.WithCancellation[T](Task`1 task, CancellationToken cancellationToken) at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken) --- End of inner exception stack trace --- at DnsClient.LookupClient.ResolveQueryAsync(IReadOnlyList`1 servers, DnsQuerySettings settings, DnsMessageHandler handler, DnsRequestMessage request, LookupClientAudit audit, CancellationToken cancellationToken) at DnsClient.LookupClient.QueryInternalAsync(DnsQuestion question, DnsQuerySettings queryOptions, IReadOnlyCollection`1 servers, CancellationToken cancellationToken) at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+MoveNext() at System.Application.Services.Implementation.DnsAnalysisServiceImpl.AnalysisDomainIpAsync(String hostNameOrAddress, IPAddress[] dnsServers, Boolean isIPv6, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult() at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 130 at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 132 at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Core|91_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 30 at System.Application.Services.Implementation.HttpServer.Middleware.HttpReverseProxyMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) at System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) at System.Application.Services.Implementation.HttpServer.Middleware.HttpProxyPacMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) at System.Application.Services.Implementation.HttpServer.Middleware.HttpLocalRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)</Data> 
  </EventData>
  </Event>
```

### 你期望发生的行为？

恢复正常运行，不再崩溃

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Tiamat9527** [comment]
客户端版本判定有误

**Comment by Lightczx** [comment]
@Tiamat9527  你的系统是正常的系统么，有进行修改/关闭部分服务/安装美化软件么

**Comment by Tiamat9527** [comment]
使用1.12.4版本时也遇到过这个问题，此前已参照
【[Bug]: 遇到了无法恢复的致命错误 #2240 】
的解决方法，前往数据文件夹删除了默认位置在 %USERPROFILE%\Documents\Hutao的Metadata 文件夹，
但当时未解决此问题。
今早更新至1.12.5版本后仍然复现该问题。
系统除推迟自动更新外，未修改其他配置。

**Comment by Lightczx** [comment]
检查Windows Update服务的状态

**Comment by Tiamat9527** [comment]
检查前为未启动状态，启动方式为手动。
检查后已改为自动启动，并已启动Windows Update服务

**Comment by Tiamat9527** [comment]
Windows Update服务改为自动启动后已解决
