### ISSUE TITLE
无法自己选择游戏路径

### ISSUE THREAD

**Issue by yang429-end** [DGP-Studio/Snap.Hutao#2292]
### Windows 版本

10.0.22000.2538

### Snap Hutao 版本

1.12.7.0

### 设备 ID

8AA10A1E347310E44B9535AEA5C17021

### 问题分类

游戏启动器

### 发生了什么？

Exception Data:
----------------------------------------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\1\原神bilbil\Genshin Impact\config.ini'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenRead(String path)
   at Snap.Hutao.Service.Game.Locator.RegistryLauncherGameLocator.LocateGamePathAsync(String registryKey, String executableName) in C:\Users\Public\appveyor\Snap.Hutao-cw172wqqkdjl9pus\src\Snap.Hutao\Snap.Hutao\Service\Game\Locator\RegistryLauncherGameLocator.cs:line 94
   at Snap.Hutao.Service.Game.Locator.RegistryLauncherGameLocator.LocateMultipleGamePathAsync() in C:\Users\Public\appveyor\Snap.Hutao-cw172wqqkdjl9pus\src\Snap.Hutao\Snap.Hutao\Service\Game\Locator\RegistryLauncherGameLocator.cs:line 38
   at Snap.Hutao.Service.Game.PathAbstraction.GamePathService.SilentLocateAllGamePathAsync() in C:\Users\Public\appveyor\Snap.Hutao-cw172wqqkdjl9pus\src\Snap.Hutao\Snap.Hutao\Service\Game\PathAbstraction\GamePathService.cs:line 50
   at Snap.Hutao.ViewModel.Game.LaunchGameViewModel.LoadOverrideAsync() in C:\Users\Public\appveyor\Snap.Hutao-cw172wqqkdjl9pus\src\Snap.Hutao\Snap.Hutao\ViewModel\Game\LaunchGameViewModel.cs:line 185
   at Snap.Hutao.ViewModel.Abstraction.ViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-cw172wqqkdjl9pus\src\Snap.Hutao\Snap.Hutao\ViewModel\Abstraction\ViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
#2289
