### ISSUE TITLE
[Bug]: 导入成就时出现错误程序崩溃

### ISSUE THREAD

**Issue by CreamPig233** [DGP-Studio/Snap.Hutao#2307]
### Windows 版本

26100.2605

### Snap Hutao 版本

1.12.8.0

### 问题分类

成就管理

### 发生了什么？

背景说明：已开启代理工具，使用TUN模式，此时Hutao可正常联网

复现过程：
1.正常启动hutao
2.loopback提示窗口点击取消
3.关闭主窗口
4.打开YaeAchievement，导入成就
【! 此时未显示导入成就窗口】
5.loopback提示窗口点击取消
6.关闭主窗口
7.打开YaeAchievement，导入成就
8.发生崩溃

https://github.com/user-attachments/assets/d4ff170f-e795-48ed-8fa9-868d1f6ce254

![Image](https://github.com/user-attachments/assets/a32aeec2-457b-43ef-a83d-25ffc98ba079)

Snap Hutao 1.12.8.0
Windows 10.0.26100.2605
System Architecture: X64
Process Architecture: X64
Framework: .NET 9.0.0

Exception Data:
[string]:Description:某个异步操作没有正常启动。

[string]:RestrictedDescription:Only a single ContentDialog can be open at any time.
[string]:RestrictedErrorReference:
[string]:RestrictedCapabilitySid:
[WinRT.ObjectReferenceWithContext<WinRT.Interop.IUnknownVftbl>]:__RestrictedErrorObjectReference:WinRT.ObjectReferenceWithContext`1[WinRT.Interop.IUnknownVftbl]
[bool]:__HasRestrictedLanguageErrorObject:False
----------------------------------------
System.Runtime.InteropServices.COMException (0x80000019): 某个异步操作没有正常启动。

Only a single ContentDialog can be open at any time.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at Snap.Hutao.Factory.ContentDialog.ContentDialogQueue.<>c__DisplayClass9_0.<<EnqueueAndShowAsync>b__0>d.MoveNext() in C:\Users\Public\appveyor\Snap.Hutao-356hyp21t1wc7wck\src\Snap.Hutao\Snap.Hutao\Factory\ContentDialog\ContentDialogQueue.cs:line 38
--- End of stack trace from previous location ---
   at Snap.Hutao.Factory.ContentDialog.ContentDialogFactory.CreateForConfirmCancelAsync(String title, String content, ContentDialogButton defaultButton) in C:\Users\Public\appveyor\Snap.Hutao-356hyp21t1wc7wck\src\Snap.Hutao\Snap.Hutao\Factory\ContentDialog\ContentDialogFactory.cs:line 55
   at Snap.Hutao.ViewModel.TitleViewModel.CheckProxyAndLoopbackAsync() in C:\Users\Public\appveyor\Snap.Hutao-356hyp21t1wc7wck\src\Snap.Hutao\Snap.Hutao\ViewModel\TitleViewModel.cs:line 198
   at Snap.Hutao.ViewModel.TitleViewModel.LoadOverrideAsync() in C:\Users\Public\appveyor\Snap.Hutao-356hyp21t1wc7wck\src\Snap.Hutao\Snap.Hutao\ViewModel\TitleViewModel.cs:line 68
   at Snap.Hutao.ViewModel.Abstraction.ViewModel.LoadAsync() in C:\Users\Public\appveyor\Snap.Hutao-356hyp21t1wc7wck\src\Snap.Hutao\Snap.Hutao\ViewModel\Abstraction\ViewModel.cs:line 46
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()

### 你期望发生的行为？

猜测是loopback窗口与成就导入窗口发生冲突；

预期成果为两窗口不冲突，且成就可以成功导入

### 最后一步

- [x] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Mikachu2333** [comment]
@CreamPig233 请检查视频格式是否正确

**Comment by Mikachu2333** [comment]
坏消息，更新弹窗一样可以导致此种类型的崩溃
