### ISSUE TITLE
[Network]: 无法下载资源文件, 无法连接资源站

### ISSUE THREAD

**Issue by liblaf** [DGP-Studio/Snap.Hutao#348]
### 提交你的网络诊断报告

```
正在诊断网络环境...
这可能需要至多10分钟，请耐心等待。
诊断程序可以在最小化的情况下运行，结束后将生成报告文件。

本地时间: 2023-01-09 16:28:10
本机时区: China Standard Time

本地 DNS: 192.168.1.1

当前 IP：183.210.179.231  来自于：中国 江苏 南通  移动

====================
正在检查 元数据 的网络连接情况
IP 地址: 36.156.217.182

Pinging hcdnd101.smev6.cdnhwcibv122.com [2409:8c20:1834:508::31] with 32 bytes of data:
Reply from 2409:8c20:1834:508::31: time=8ms
Reply from 2409:8c20:1834:508::31: time=7ms
Reply from 2409:8c20:1834:508::31: time=9ms
Reply from 2409:8c20:1834:508::31: time=8ms

Ping statistics for 2409:8c20:1834:508::31:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 7ms, Maximum = 9ms, Average = 8ms


正在进行 traceroute 测试，请耐心等待...

Tracing route to hcdnd101.smev6.cdnhwcibv122.com [2409:8c20:1834:508::31]
over a maximum of 30 hops:

  1     2 ms     1 ms     1 ms  2409:8a20:5c04:ae4:5a91:53ff:fe4e:f6b1
  2     5 ms     4 ms     4 ms  2409:8020:60:139::1
  3     7 ms     5 ms     5 ms  2409:8020:60:19e::
  4    14 ms     8 ms     9 ms  2409:8020:0:603e::
  5    12 ms     8 ms     8 ms  2409:8020:3034:1c18::1
  6   172 ms    11 ms    11 ms  2409:8c20:1834:11:108::3
  7    25 ms     8 ms     7 ms  fc01::1
  8    11 ms     8 ms     8 ms  2409:8c20:1834:508::31

Trace complete.


====================
正在检查 静态资源 - 1 的网络连接情况
IP 地址: 81.28.12.12
Traceback (most recent call last):
  File "main.py", line 93, in <module>
  File "subprocess.py", line 420, in check_output
  File "subprocess.py", line 524, in run
subprocess.CalledProcessError: Command 'ping static.hut.ao' returned non-zero exit status 1.
[10792] Failed to execute script 'main' due to unhandled exception!
```

### 你的地理位置

江苏

### 你的运营商

中国移动

### 你的问题

完全无法连接服务器

### 你的问题（补充）

无法连接到静态资源站, [Snap Genshin 服务监控](https://status.snapgenshin.com) 显示资源站失效已经有一段时间了, 不知道是否相关.

**Comment by Masterain98** [comment]
问题来源是DNS记录为空。这里看到你用的DNS为你的路由器（应该是在本机上使用了自动DNS），所以可以查一下你路由器上的DNS服务器设置。

**Comment by Masterain98** [comment]
三次ping命令结果为全部丢包，如果有代理的话建议先全局代理试一下能不能解决，今天稍晚些我们调整一下网络。

**Comment by liblaf** [comment]
> 三次ping命令结果为全部丢包，如果有代理的话建议先全局代理试一下能不能解决，今天稍晚些我们调整一下网络。

全局代理可以解决 ✅
