### ISSUE TITLE
[Bug]: 登录HoYoLab账号时程序崩溃，无法正确获取角色信息

### ISSUE THREAD

**Issue by sacrish** [DGP-Studio/Snap.Hutao#795]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22621.1848

### Snap Hutao 版本

1.6.50

### 设备 ID

CC993910543BF591890630719F34F6FA

### 问题分类

其它

### 发生了什么？

在程序内网页登录HoYoLab后，点击「我已登录」，程序崩溃。

重新启动程序后，在角色菜单里可以看到一个 user_xxxxxxxxx，但无法选择角色，各功能均无法使用。且点击「刷新Cookie」也会导致程序崩溃。

![Screenshot 2023-07-10 220915](https://github.com/DGP-Studio/Snap.Hutao/assets/8361680/9eebc5a8-e2d9-42c7-b290-e0d6c982de5f)

**Comment by sacrish** [comment]
经过我的排查，原因可能与HoYoLab的昵称有关。

之前我的HoYoLab个人资料是没有添加昵称的（默认显示的便是上面截图中的 user id）。设置昵称后，在胡桃里登录正常了。

**Comment by Xhichn** [comment]
@Lightczx Snap.Hutao 1.7.0.0 登录HoYoLAB账号也会导致程序崩溃

通过网页登录HoYoLab后，点击「我已登录」，程序立即崩溃，日志显示与 PassportClientOversea 的构造器有关

尝试修改 [PassportClientOversea.cs Line 15](https://github.com/DGP-Studio/Snap.Hutao/blob/945a53a737ec8785948e7879f56130d7e5bcd397/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Passport/PassportClientOversea.cs#L15C18-L15C18) 处的代码可以解决问题

```C#
[ConstructorGenerated(ResolveHttpClient = true)]
```

<details>
<summary>崩溃日志</summary>

```
Exception Data:
----------------------------------------
System.InvalidOperationException: A suitable constructor for type 'Snap.Hutao.Web.Hoyolab.Passport.PassportClientOversea' could not be located. Ensure the type is concrete and all parameters of a public constructor are either registered as services or passed as arguments. Also ensure no extraneous arguments are provided.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.Cache.<>c.<.cctor>b__7_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.Cache.get_Activator()
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient](IServiceProvider s, IHttpClientBuilder builder)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass10_0`1.<AddTypedClientCore>b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Core.DependencyInjection.Abstraction.OverseaSupportFactory`3.Create(Boolean isOversea) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\Abstraction\OverseaSupportFactory.cs:line 19
   at Snap.Hutao.Service.User.UserInitializationService.TrySetUserLTokenAsync(User user, CancellationToken token) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\User\UserInitializationService.cs:line 100
   at Snap.Hutao.Service.User.UserInitializationService.InitializeUserAsync(User user, CancellationToken token) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\User\UserInitializationService.cs:line 69
   at Snap.Hutao.Service.User.UserInitializationService.CreateOrDefaultUserFromCookieAsync(Cookie cookie, Boolean isOversea, CancellationToken token) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\User\UserInitializationService.cs:line 44
   at Snap.Hutao.Service.User.UserService.TryCreateUserAndAddAsync(Cookie cookie, Boolean isOversea) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\User\UserService.cs:line 204
   at Snap.Hutao.Service.User.UserService.ProcessInputCookieAsync(Cookie cookie, Boolean isOversea) in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\User\UserService.cs:line 157
   at Snap.Hutao.View.Page.LoginHoyoverseUserPage.HandleCurrentCookieAsync() in C:\Users\Studio\source\repos\Xhichn\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\View\Page\LoginHoyoverseUserPage.xaml.cs:line 102
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
程序“[48108] Snap.Hutao.exe”已退出，返回值为 0 (0x0)。
```
</details>

**Comment by Lightczx** [comment]
> @Lightczx Snap.Hutao 1.7.0.0 登录HoYoLAB账号也会导致程序崩溃
> 
> 通过网页登录HoYoLab后，点击「我已登录」，程序立即崩溃，日志显示与 PassportClientOversea 的构造器有关
> 
> 尝试修改 [PassportClientOversea.cs Line 15](https://github.com/DGP-Studio/Snap.Hutao/blob/945a53a737ec8785948e7879f56130d7e5bcd397/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Passport/PassportClientOversea.cs#L15C18-L15C18) 处的代码可以解决问题
> 
> ```cs
> [ConstructorGenerated(ResolveHttpClient = true)]
> ```
> 
> 崩溃日志

相关代码已经push 到 develop 分支

**Comment by Lightczx** [comment]
1.7.3会修复此问题，目前商店中已经有1.7.2了
