### ISSUE TITLE
[Bug]: 非管理员模式无法启动

### ISSUE THREAD

**Issue by ZSZHISHI** [DGP-Studio/Snap.Hutao#928]
### 检查清单

- [ ] 我并未完整阅读[胡桃工具箱文档](https://hut.ao/advanced/FAQ.html)
- [ ] 我不知道文档站的导航栏中有**搜索功能**，也没有搜索过相关关键词
- [ ] 我使用的操作系统是不[受支持的版本](https://hut.ao/quick-start.html#%E6%9C%80%E4%BD%8E%E7%B3%BB%E7%BB%9F%E8%A6%81%E6%B1%82)
- [ ] 我没有**通过搜索功能**确认其他人提出过相同或类似的问题
- [ ] 我不明白上述的勾选项是**一个有助于快速排查问题的检查清单**，而是随手确认的选项

### Windows 版本

22612.2283

### Snap Hutao 版本

1.7.4.0

### 设备 ID

E51371D8EDD18FFA678ABB748DFE1D3F

### 问题分类

游戏启动器

### 发生了什么？

当我更新至此版本后，它提醒我需要更改游戏路径。但由于我是管理员模式，所以无法更改。于是当我尝试通过关闭Snap Hutao并通过不使用管理员模式打开时，它却没有任何响应。当我多次尝试后，在任务管理器发现Snap Hutao只会出现一小会儿随后消失。但当我再次尝试使用管理员模式打开时，Snap Hutao却能顺利启动。且在我重新安装Snap Hutao和重新启动电脑后此问题仍未解决

**Comment by Lightczx** [comment]
检查下eventvwr里面有没有相关的 .NET Runtime Error @ZSZHISHI

**Comment by ZSZHISHI** [comment]
日志名称:          Application
来源:            .NET Runtime
日期:            2023/9/14 22:16:08
事件 ID:         1026
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           安好的COMPUTER
描述:
Application: Snap.Hutao.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at Snap.Hutao.Core.DependencyInjection.IocConfiguration.AddDbContextCore(IServiceProvider provider, DbContextOptionsBuilder builder) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\IocConfiguration.cs:line 48
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Service.Abstraction.DbStoreOptions.GetOption[T](T& storage, String key, Func`2 deserializer, T defaultValue) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\Abstraction\DbStoreOptions.cs:line 114
   at Snap.Hutao.Service.AppOptions.get_CurrentCulture() in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\AppOptions.cs:line 103
   at Snap.Hutao.Core.DependencyInjection.DependencyInjection.Initialize() in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\DependencyInjection.cs:line 43
   at Snap.Hutao.Program.Main(String[] args) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Program.cs:line 34

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-09-14T14:16:08.0222218Z" />
    <EventRecordID>33304</EventRecordID>
    <Correlation />
    <Execution ProcessID="11448" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>安好的COMPUTER</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Snap.Hutao.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteScalar()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteScalar(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetAppliedMigrations(DatabaseFacade databaseFacade)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetPendingMigrations(DatabaseFacade databaseFacade)
   at Snap.Hutao.Core.DependencyInjection.IocConfiguration.AddDbContextCore(IServiceProvider provider, DbContextOptionsBuilder builder) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\IocConfiguration.cs:line 48
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.&lt;&gt;c__DisplayClass17_0`1.&lt;AddCoreServices&gt;b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.&lt;&gt;c__DisplayClass2_0.&lt;RealizeService&gt;b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Snap.Hutao.Service.Abstraction.DbStoreOptions.GetOption[T](T&amp; storage, String key, Func`2 deserializer, T defaultValue) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\Abstraction\DbStoreOptions.cs:line 114
   at Snap.Hutao.Service.AppOptions.get_CurrentCulture() in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Service\AppOptions.cs:line 103
   at Snap.Hutao.Core.DependencyInjection.DependencyInjection.Initialize() in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Core\DependencyInjection\DependencyInjection.cs:line 43
   at Snap.Hutao.Program.Main(String[] args) in D:\Projects\Snap.Hutao\src\Snap.Hutao\Snap.Hutao\Program.cs:line 34
</Data>
  </EventData>
</Event>

**Comment by ZSZHISHI** [comment]
当我第一次更新后是首次管理员模式启动，后面重新安装后没有，但还是打不开

**Comment by Lightczx** [comment]
那可能要删了重开了，先导出重要记录

**Comment by ZSZHISHI** [comment]
什么意思？我不是很理解？重置Windows吗？

**Comment by Masterain98** [comment]
- 在设置里选择删除全部用户数据 
  - 或移除 `Userdata.db` 文件
- 重启 Snap Hutao
上述步骤会导致你丢失全部的程序数据，所以你需要先通过导出功能备份你的祈愿记录和成就记录。

**Comment by ZSZHISHI** [comment]
两者都试了却仍然无效

**Comment by Masterain98** [comment]
无效是指还是存在“非管理员模式无法启动”这个问题吗？

**Comment by ZSZHISHI** [comment]
是的

**Comment by Lightczx** [comment]
整个数据文件夹删了重装看一下吧

**Comment by ZSZHISHI** [comment]
将Userdata.db所在的整个Hutao文件夹删掉后再重装吗？我已经试过了仍不能解决此问题

**Comment by Lightczx** [comment]
你没换个数据文件夹的路径吧

**Comment by Lightczx** [comment]
目前来看就是你的 `userdata.db` 放在了一个非管理员权限无法写入的地方

**Comment by ZSZHISHI** [comment]
没换过

**Comment by Lightczx** [comment]
除了重装系统没啥好的办法了，这个问题挺莫名其妙的

**Comment by Lightczx** [comment]
closing as this can't be resolved by us
