### ISSUE TITLE
[Bug]: 主页活动公告拉到底部时卡死

### ISSUE THREAD

**Issue by ZeroXrainy** [DGP-Studio/Snap.Hutao#984]
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已修复](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E4%BF%AE%E5%A4%8D)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

23555.1000

### Snap Hutao 版本

1.7.6.0

### 设备 ID

5356D7179EAC575E96256F0AAD45F5A9

### 问题分类

用户界面

### 发生了什么？

主页活动公告拉到底部时卡死崩溃
```
日志名称:          Application
来源:            .NET Runtime
日期:            2023/10/2 21:26:29
事件 ID:         1000
任务类别:          无
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           Windows
描述:
Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware
EventId: 0
SpanId: 3b22912472799437
TraceId: a25d01013f7812307b3fd1247702d3c0
ParentId: 0000000000000000
ConnectionId: 0HMU392BI61H0
RequestId: 0HMU392BI61H0:00000059
RequestPath: /OneCollector/1.0/

POST https://functional.events.data.microsoft.com/OneCollector/1.0/ responded 502 in 10012.9112 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 13.89.179.9 timed out.) (functional.events.data.microsoft.com:443)
 ---> System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 13.89.179.9 timed out.)
 ---> System.TimeoutException: HTTP connection to 13.89.179.9 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-10-02T13:26:29.2512375Z" />
    <EventRecordID>1155</EventRecordID>
    <Correlation />
    <Execution ProcessID="6344" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Windows</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: System.Application.Services.Implementation.HttpServer.Middleware.RequestLoggingMiddleware
EventId: 0
SpanId: 3b22912472799437
TraceId: a25d01013f7812307b3fd1247702d3c0
ParentId: 0000000000000000
ConnectionId: 0HMU392BI61H0
RequestId: 0HMU392BI61H0:00000059
RequestPath: /OneCollector/1.0/

POST https://functional.events.data.microsoft.com/OneCollector/1.0/ responded 502 in 10012.9112 ms
System.Net.Http.HttpRequestException: Could not find any IP that can be successfully connected. (HTTP connection to 13.89.179.9 timed out.) (functional.events.data.microsoft.com:443)
 ---&gt; System.AggregateException: Could not find any IP that can be successfully connected. (HTTP connection to 13.89.179.9 timed out.)
 ---&gt; System.TimeoutException: HTTP connection to 13.89.179.9 timed out.
   --- End of inner exception stack trace ---
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.ConnectCallback(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Application.Services.Implementation.Http.ReverseProxyHttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)
</Data>
  </EventData>
</Event>
```

![屏幕截图 2023-10-02 211032](https://github.com/DGP-Studio/Snap.Hutao/assets/146737891/dae923cd-7f6e-47d8-92ad-a1aadd743848)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Lightczx** [comment]
winui 3 问题
